/* EMPIRE OF GODS demo — the DATA shim js/assets.js expects.
   One original sprite set per god, generated by tools/artgen (all sets share one 92px master
   layout, so they share one scale and stand the same height on the floor). */
'use strict';

const DATA = { AGENT: {} };
DATA.SKINS = {
  zeus:       { name: 'Zeus',       set: 'zeus',       scale: 0.40 },
  hera:       { name: 'Hera',       set: 'hera',       scale: 0.40 },
  athena:     { name: 'Athena',     set: 'athena',     scale: 0.40 },
  hermes:     { name: 'Hermes',     set: 'hermes',     scale: 0.40 },
  hephaestus: { name: 'Hephaestus', set: 'hephaestus', scale: 0.40 },
  apollo:     { name: 'Apollo',     set: 'apollo',     scale: 0.40 },
  hades:      { name: 'Hades',      set: 'hades',      scale: 0.40 },
  dionysus:   { name: 'Dionysus',   set: 'dionysus',   scale: 0.40 },
};
DATA.DEFAULT_SKIN = 'zeus';
